// Dijana oleh timeline.py — jangan edit terus.
window.LINES = [
  {"id": "01", "start": 0.3, "end": 4.9, "text": "Mak ayah dah lama teringin nak ada penapis air dekat rumah?"},
  {"id": "02", "start": 5.25, "end": 9.35, "text": "Atau mungkin mak dekat kampung sendiri pernah cakap,"},
  {"id": "03", "start": 9.7, "end": 14.35, "text": "Kalau ada penapis air dekat kampung, kan senang…"},
  {"id": "04", "start": 15.0, "end": 19.45, "text": "Kita yang duduk jauh ni, kadang-kadang rasa serba salah."},
  {"id": "05", "start": 19.8, "end": 24.5, "text": "Dekat rumah sendiri, air panas, air sejuk, semua dah ada."},
  {"id": "06", "start": 24.85, "end": 33.8, "text": "Tapi dekat rumah mak ayah di kampung, masih kena masak air, tunggu air panas, atau isi air dalam bekas macam biasa."},
  {"id": "07", "start": 34.15, "end": 39.35, "text": "Dah lama kita fikir nak bantu. Nak belikan penapis air untuk mak ayah."},
  {"id": "08", "start": 39.9, "end": 46.5, "text": "Mak ayah tak perlukan produk paling canggih. Tapi apa yang paling senang untuk mak ayah guna."},
  {"id": "09", "start": 46.85, "end": 51.7, "text": "Sebab bagi kita, model yang banyak elektronik mungkin nampak lagi moden."},
  {"id": "10", "start": 52.05, "end": 55.65, "text": "Tapi bagi mak ayah, yang dah biasa dengan barang-barang manual…"},
  {"id": "11", "start": 56.0, "end": 61.35, "text": "Pulas tombol suhu, tekan tuil, terus keluar air. Itu yang lagi senang."},
  {"id": "12", "start": 61.7, "end": 64.45, "text": "Tak perlu pening tengok nombor LED."},
  {"id": "13", "start": 64.8, "end": 69.05, "text": "Takkan nak ambil air pun, kena ambil spek membaca dulu?"},
  {"id": "14", "start": 69.6, "end": 77.2, "text": "Yang penting, air panas, air sejuk, dan air biasa, semuanya dah tersedia bila diperlukan."},
  {"id": "15", "start": 77.55, "end": 84.9, "text": "Nak buat kopi? Tekan. Nak buat teh? Tekan. Nak bancuh susu? Air panas dah tersedia."},
  {"id": "16", "start": 85.45, "end": 90.7, "text": "Dan sebagai anak, kita pun kena fikir satu lagi benda. Bajet mampu milik."},
  {"id": "17", "start": 91.05, "end": 94.0, "text": "Sebab kalau adik-beradik nak kongsi bayar pun, boleh."},
  {"id": "18", "start": 94.35, "end": 100.75, "text": "Tahun ni kita bayar. Tahun depan, mungkin abang pula. Tahun seterusnya, adik pula."},
  {"id": "19", "start": 101.1, "end": 106.25, "text": "Gilir-gilir. Jadi tak terasa sangat membebankan seorang."},
  {"id": "20", "start": 107.0, "end": 114.1, "text": "Kalau untuk mak ayah dekat kampung, salah satu model yang boleh dipertimbangkan ialah, Coway Neo Plus."},
  {"id": "21", "start": 114.45, "end": 118.85, "text": "Ada tiga suhu air. Panas, sejuk, dan suhu bilik."},
  {"id": "22", "start": 119.2, "end": 121.5, "text": "Saiz pun sesuai untuk keluarga kecil."},
  {"id": "23", "start": 121.85, "end": 129.95, "text": "Kalau dekat rumah mak ayah cuma dua orang, atau ada adik yang masih tinggal bersama, tak lah perlukan model dengan tangki yang terlalu besar."},
  {"id": "24", "start": 130.3, "end": 134.85, "text": "Yang penting, cukup, mudah, dan praktikal untuk kegunaan harian."},
  {"id": "25", "start": 135.5, "end": 138.5, "text": "Dan sekarang, Neo Plus ni ada harga promosi."},
  {"id": "26", "start": 138.85, "end": 145.95, "text": "Serendah lima puluh sembilan ringgit sebulan. Jimat empat puluh lima ringgit, dari harga asal seratus empat ringgit.", "sub": "Serendah RM59 sebulan. Jimat RM45, dari harga asal RM104."},
  {"id": "27", "start": 146.3, "end": 152.0, "text": "Dan ada double promo. Tujuh bulan pertama, cuma dua puluh ringgit sebulan!", "sub": "Dan ada double promo. 7 bulan pertama, cuma RM20 sebulan!"},
  {"id": "28", "start": 152.35, "end": 155.25, "text": "Penghantaran dan pemasangan pun percuma."},
  {"id": "29", "start": 155.9, "end": 161.3, "text": "Jadi kalau memang dah lama terfikir nak belikan penapis air untuk mak ayah…"},
  {"id": "30", "start": 161.65, "end": 166.05, "text": "mungkin sekarang, masa yang sesuai untuk buatkan hidup mereka sedikit lebih mudah."},
  {"id": "31", "start": 166.4, "end": 168.75, "text": "Klik WhatsApp sekarang, untuk tanya detail."}
];
window.DURATION = 170.95;
window.TIMING = {CPS: 16.5, P_STOP: 0.35, P_COMMA: 0.12};
